# This file was generated by the {rix} R package v0.9.0 on 2024-07-29
# with following call:
# >rix(r_ver = "bleeding_edge",
#  > r_pkgs = c("dplyr",
#  > "ggplot2",
#  > "data.table"),
#  > project_path = ".")
# It uses the `rstats-on-nix` fork of `nixpkgs` which provides bleeding
# edge packages and R.
# Only use bleeding edge packages if absolutely needed!
# Read more on https://b-rodrigues.github.io/rix/articles/z-bleeding_edge.html
# Report any issues to https://github.com/b-rodrigues/rix
let
 pkgs = import (fetchTarball "https://github.com/rstats-on-nix/nixpkgs/archive/refs/heads/r-daily.tar.gz") {};
 
  rpkgs = builtins.attrValues {
    inherit (pkgs.rPackages) 
      dplyr
      ggplot2
      data_table;
  };
    
  system_packages = builtins.attrValues {
    inherit (pkgs) 
      R
      glibcLocales
      nix;
  };
  
in

pkgs.mkShell {
  LOCALE_ARCHIVE = if pkgs.system == "x86_64-linux" then  "${pkgs.glibcLocales}/lib/locale/locale-archive" else "";
  LANG = "en_US.UTF-8";
   LC_ALL = "en_US.UTF-8";
   LC_TIME = "en_US.UTF-8";
   LC_MONETARY = "en_US.UTF-8";
   LC_PAPER = "en_US.UTF-8";
   LC_MEASUREMENT = "en_US.UTF-8";

  buildInputs = [  rpkgs  system_packages   ];
  
}
